hl.on("hyprland.start", function()
    hl.exec_cmd("killall xdg-desktop-portal; /usr/lib/xdg-desktop-portal &")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("/usr/bin/quickshell")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
end)