animations {
    enabled = true

    # curves
    bezier = decel,     0.05, 0.9, 0.1, 1.0
    bezier = smoothOut, 0.16, 1, 0.3, 1
    bezier = wsSmooth,  0.22, 1, 0.36, 1
    bezier = linear,    0, 0, 1, 1

    # windows
    animation = windows,      1, 6, wsSmooth, slide
    animation = windowsIn,    1, 6, wsSmooth, slide
    animation = windowsOut,   1, 5, wsSmooth, slide
    animation = fade,         1, 5, smoothOut
    animation = border,       1, 8, smoothOut
    animation = borderangle,  1, 30, linear, loop

    # workspaces
    animation = workspaces,        1, 7, wsSmooth, slide
    animation = specialWorkspace,  1, 7, wsSmooth, slidevert

    # layers
    animation = layers,       1, 6, decel
    animation = layersIn,     1, 6, decel,     slide
    animation = layersOut,    1, 5, smoothOut, slide
}
