# env & vars
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/variables.conf

# appearance
source = ~/.cache/wal/colors-hyprland.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/animations.conf

# input & rules
source = ~/.config/hypr/keybinds.conf
source = ~/dotfiles/local/user-keybinds.conf
source = ~/.config/hypr/windowrules.conf

# hw & startup
source = ~/.config/hypr/startup.conf

# local overrides 
source = ~/dotfiles/local/hypr-local.conf