# core
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# theme
exec-once = awww-daemon

# shell
exec-once = /usr/bin/quickshell

# cursor
exec-once = hyprctl setcursor Bibata-Modern-Classic 24