# global 
windowrule {
    name        = global-glass
    match:class = .*
    opacity     = 0.85 override 0.80 override 1.0 override
    border_size = 0
}

# floating 
windowrule {
    name        = system-dialogs
    match:class = .*(xdg-desktop-portal-gtk|zenity|kdialog).*
    float       = on
    size        = 800 600
    center      = on
}

windowrule {
    name        = blueman-popup
    match:class = ^(blueman-manager)$
    float       = on
    size        = 700 500
    center      = on
}

windowrule {
    name        = pulseaudio-popup
    match:class = ^(pavucontrol|org\.pulseaudio\.pavucontrol)$
    float       = on
    size        = 700 500
    center      = on
    animation   = popin
}

# performance
windowrule {
    name        = games-no-glass
    match:class = ^(steam_app_.*|gamescope|.*\.exe)$
    opacity     = 1.0 override 1.0 override 1.0 override
    no_blur     = on
    rounding    = 0
}

windowrule {
    name        = media-no-glass
    match:class = ^(mpv|vlc|io\.mpv\.Mpv|org\.videolan\.VLC)$
    opacity     = 1.0 override 1.0 override 1.0 override
    no_blur     = on
}

windowrule {
    name             = fullscreen-no-glass
    match:fullscreen = 1
    opacity          = 1.0 override 1.0 override 1.0 override
    no_blur          = on
}

windowrule {
    name        = creative-no-glass
    match:class = ^(org\.kde\.krita|GIMP|Gimp|blender|kdenlive|com\.obsproject\.Studio)$
    opacity     = 1.0 override 1.0 override 1.0 override
}

# layer rules
layerrule {
    name            = quickshell-sidebar
    match:namespace = quickshell
    blur            = on
    ignore_alpha    = 0.1
    xray            = on
}

layerrule {
    name            = sidebar-logic
    match:namespace = quickshell-sidebar
    blur            = on
    ignore_alpha    = 0.1
    xray            = on
    animation       = slide right
}

layerrule {
    name            = rofi-glass
    match:namespace = rofi
    blur            = on
    ignore_alpha    = 0.2
    xray            = on
    animation       = slide top
}

layerrule {
    name            = wallpicker-glass
    match:namespace = wallpicker
    blur            = on
    xray            = on
    ignore_alpha    = 0.5
    animation       = slide bottom
}

layerrule {
    name            = disable-picker-anim
    match:namespace = ^(hyprpicker)$
    no_anim         = 1
}

layerrule {
    name            = topbar-glass
    match:namespace = quickshell-topbar
    blur            = on
    ignore_alpha    = 0.5
    xray            = on
    animation       = slide top
}

layerrule {
    name            = keybinds-glass
    match:namespace = quickshell-keybinds
    blur            = on
    ignore_alpha    = 0.5
    xray            = on
}