include ~/.cache/wal/colors-kitty.conf

font_family                JetBrainsMono Nerd Font
font_size                  11.0

background_opacity         0.75
dynamic_background_opacity yes

window_padding_width       25
hide_window_decorations    yes
confirm_os_window_close    0

repaint_delay              10
input_delay                3
sync_to_monitor            yes
wayland_enable_ime         no
