include ~/.cache/wal/colors-kitty.conf

font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.0
modify_font cell_height 110%
modify_font underline_position 2
modify_font underline_thickness 140%

cursor_shape                 beam
cursor_beam_thickness        1.6
cursor_blink_interval        0.6
cursor_trail                 3
cursor_trail_decay           0.08 0.22
cursor_trail_start_threshold 2

background_opacity         0.70
dynamic_background_opacity yes
window_padding_width       28
hide_window_decorations    yes
confirm_os_window_close    0

tab_bar_edge          bottom
tab_bar_style         powerline
tab_powerline_style   slanted
tab_bar_min_tabs      2
tab_title_template    " {index} {title} "
active_tab_font_style bold

url_style            curly
underline_hyperlinks hover
mouse_hide_wait      2.0
scrollback_lines     10000
enable_audio_bell    no
visual_bell_duration 0

repaint_delay      8
input_delay        2
sync_to_monitor    yes
wayland_enable_ime no
